# Generated by Django 4.0.5 on 2022-07-22 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0003_rename_user_userinfo_alter_userinfo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointment_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=40)),
                ('contact', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField(max_length=200)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate.userinfo')),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
    ]
