# Generated by Django 4.0.5 on 2022-07-22 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authenticate', '0003_rename_user_userinfo_alter_userinfo_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice_Vacancy',
            fields=[
                ('notice_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('publish_date', models.DateField()),
                ('image', models.FileField(default='default.png', upload_to='static/images/user')),
                ('description', models.TextField(max_length=200)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authenticate.userinfo')),
            ],
            options={
                'db_table': 'Notice_Vacancy',
            },
        ),
    ]
