# Generated by Django 4.0.5 on 2022-07-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice_vacancy',
            old_name='image',
            new_name='post_image',
        ),
    ]
