# Generated by Django 4.0.5 on 2022-07-22 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_rename_user_userinfo_alter_userinfo_table'),
        ('user', '0002_rename_image_notice_vacancy_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_vacancy',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authenticate.userinfo'),
        ),
    ]
