# Generated by Django 4.0.5 on 2022-07-22 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_rename_user_userinfo_alter_userinfo_table'),
        ('user', '0003_alter_notice_vacancy_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_vacancy',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authenticate.userinfo'),
        ),
    ]
