# Generated by Django 4.0.5 on 2022-07-22 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_notice_vacancy_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_vacancy',
            name='post_image',
            field=models.FileField(upload_to='static/images/user'),
        ),
    ]
