# Generated by Django 4.0.5 on 2022-07-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_notice_vacancy_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice_vacancy',
            name='post_image',
            field=models.FileField(default='default.png', upload_to='static/images/user'),
        ),
    ]
